services:
  rabbitmq:
    image: rabbitmq:3.8-alpine
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5

  receiver:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: make run-receiver

  publisher:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: make run-publisher
